"""
Document Management API Endpoints

Provides REST API for document management operations.
"""

from fastapi import APIRouter, Depends, HTTPException, UploadFile, File, status
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session
from typing import List

from backend.core.dependencies import get_db, get_current_user
from backend.services.document_service import DocumentService
from backend.models.document_schemas import (
    DocumentCreate, DocumentUpdate, DocumentResponse,
    DocumentTemplateCreate, DocumentTemplateUpdate, DocumentTemplateResponse,
    DocumentShareCreate, DocumentShareResponse,
    DocumentGenerateRequest, DocumentSearchRequest, DocumentListResponse,
    DocumentVersionResponse
)
from backend.models.user_schemas import UserResponse


router = APIRouter(prefix="/documents", tags=["documents"])


def get_document_service(db: Session = Depends(get_db)) -> DocumentService:
    """Dependency to get document service"""
    return DocumentService(db)


# Document CRUD Endpoints

@router.post("/", response_model=DocumentResponse, status_code=status.HTTP_201_CREATED)
async def create_document(
    file: UploadFile = File(...),
    name: str = None,
    description: str = None,
    type: str = "other",
    current_user: UserResponse = Depends(get_current_user),
    service: DocumentService = Depends(get_document_service)
):
    """
    Create a new document
    
    Upload a file and create a document record.
    """
    # Use filename if name not provided
    if not name:
        name = file.filename
    
    # Create document data
    document_data = DocumentCreate(
        name=name,
        description=description,
        type=type,
        file_name=file.filename,
        file_path="",  # Will be generated by service
        file_size=0,  # Will be calculated by service
        mime_type=file.content_type or "application/octet-stream"
    )
    
    try:
        document = service.create_document(
            document_data=document_data,
            file_content=file.file,
            user_id=current_user.id
        )
        return document
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to create document: {str(e)}"
        )


@router.get("/{document_id}", response_model=DocumentResponse)
async def get_document(
    document_id: int,
    current_user: UserResponse = Depends(get_current_user),
    service: DocumentService = Depends(get_document_service)
):
    """Get document by ID"""
    document = service.get_document(document_id)
    if not document:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Document not found"
        )
    return document


@router.put("/{document_id}", response_model=DocumentResponse)
async def update_document(
    document_id: int,
    document_data: DocumentUpdate,
    current_user: UserResponse = Depends(get_current_user),
    service: DocumentService = Depends(get_document_service)
):
    """Update document metadata"""
    document = service.update_document(
        document_id=document_id,
        document_data=document_data,
        user_id=current_user.id
    )
    if not document:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Document not found"
        )
    return document


@router.delete("/{document_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_document(
    document_id: int,
    current_user: UserResponse = Depends(get_current_user),
    service: DocumentService = Depends(get_document_service)
):
    """Delete a document (soft delete)"""
    success = service.delete_document(document_id, current_user.id)
    if not success:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Document not found"
        )


@router.get("/{document_id}/download")
async def download_document(
    document_id: int,
    current_user: UserResponse = Depends(get_current_user),
    service: DocumentService = Depends(get_document_service)
):
    """Download document file"""
    document = service.get_document(document_id)
    if not document:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Document not found"
        )
    
    file_path = service.get_file_path(document)
    return FileResponse(
        path=file_path,
        filename=document.file_name,
        media_type=document.mime_type
    )


# Document Versioning Endpoints

@router.post("/{document_id}/versions", response_model=DocumentResponse)
async def create_document_version(
    document_id: int,
    file: UploadFile = File(...),
    current_user: UserResponse = Depends(get_current_user),
    service: DocumentService = Depends(get_document_service)
):
    """Create a new version of a document"""
    try:
        new_version = service.create_version(
            document_id=document_id,
            file_content=file.file,
            user_id=current_user.id
        )
        if not new_version:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Document not found"
            )
        return new_version
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to create version: {str(e)}"
        )


@router.get("/{document_id}/versions", response_model=List[DocumentVersionResponse])
async def get_document_versions(
    document_id: int,
    current_user: UserResponse = Depends(get_current_user),
    service: DocumentService = Depends(get_document_service)
):
    """Get all versions of a document"""
    versions = service.get_versions(document_id)
    return versions


# Document Template Endpoints

@router.post("/templates", response_model=DocumentTemplateResponse, status_code=status.HTTP_201_CREATED)
async def create_template(
    template_data: DocumentTemplateCreate,
    current_user: UserResponse = Depends(get_current_user),
    service: DocumentService = Depends(get_document_service)
):
    """Create a new document template"""
    template = service.create_template(template_data, current_user.id)
    return template


@router.get("/templates", response_model=List[DocumentTemplateResponse])
async def list_templates(
    type: str = None,
    category: str = None,
    current_user: UserResponse = Depends(get_current_user),
    service: DocumentService = Depends(get_document_service)
):
    """List available document templates"""
    templates = service.list_templates(type=type, category=category)
    return templates


@router.get("/templates/{template_id}", response_model=DocumentTemplateResponse)
async def get_template(
    template_id: int,
    current_user: UserResponse = Depends(get_current_user),
    service: DocumentService = Depends(get_document_service)
):
    """Get template by ID"""
    template = service.get_template(template_id)
    if not template:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Template not found"
        )
    return template


@router.put("/templates/{template_id}", response_model=DocumentTemplateResponse)
async def update_template(
    template_id: int,
    template_data: DocumentTemplateUpdate,
    current_user: UserResponse = Depends(get_current_user),
    service: DocumentService = Depends(get_document_service)
):
    """Update template"""
    template = service.update_template(template_id, template_data)
    if not template:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Template not found"
        )
    return template


# Document Generation Endpoint

@router.post("/generate", response_model=DocumentResponse)
async def generate_document(
    request: DocumentGenerateRequest,
    current_user: UserResponse = Depends(get_current_user),
    service: DocumentService = Depends(get_document_service)
):
    """Generate a document from a template"""
    document = service.generate_from_template(request, current_user.id)
    if not document:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Template not found or generation failed"
        )
    return document


# Document Sharing Endpoints

@router.post("/share", response_model=DocumentShareResponse, status_code=status.HTTP_201_CREATED)
async def share_document(
    share_data: DocumentShareCreate,
    current_user: UserResponse = Depends(get_current_user),
    service: DocumentService = Depends(get_document_service)
):
    """Share a document with a user or email"""
    share = service.share_document(share_data, current_user.id)
    if not share:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Document not found"
        )
    return share


@router.get("/shared", response_model=List[DocumentResponse])
async def get_shared_documents(
    current_user: UserResponse = Depends(get_current_user),
    service: DocumentService = Depends(get_document_service)
):
    """Get documents shared with current user"""
    documents = service.get_shared_documents(current_user.id)
    return documents


@router.delete("/share/{share_id}", status_code=status.HTTP_204_NO_CONTENT)
async def revoke_share(
    share_id: int,
    current_user: UserResponse = Depends(get_current_user),
    service: DocumentService = Depends(get_document_service)
):
    """Revoke a document share"""
    success = service.revoke_share(share_id, current_user.id)
    if not success:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Share not found"
        )


# Document Search Endpoint

@router.post("/search", response_model=DocumentListResponse)
async def search_documents(
    search_request: DocumentSearchRequest,
    current_user: UserResponse = Depends(get_current_user),
    service: DocumentService = Depends(get_document_service)
):
    """Search documents with filters"""
    documents, total = service.search_documents(search_request, current_user.id)
    
    return DocumentListResponse(
        documents=documents,
        total=total,
        limit=search_request.limit,
        offset=search_request.offset
    )
