# ---------- SERVER ----------
[server]
headless = false
fileWatcherType = "poll"           # "auto"|"watchdog"|"poll"|"none"
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 512                 # MB
# Stabilität & Performance
runOnSave = true                    # Auto-reload bei Dateiänderungen
enableStaticServing = true          # Statische Dateien effizienter bereitstellen
enableWebsocketCompression = true   # WebSocket Kompression für bessere Performance
port = 8501                         # Standard-Port (funktioniert mit developmentMode=false)
address = "localhost"               # Server-Adresse
baseUrlPath = ""                    # Base URL Path für Reverse Proxy
# Memory & Connection Management
maxMessageSize = 200                # Max WebSocket Message Size in MB

# ---------- BROWSER ----------
[browser]
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false            # Keine Telemetrie an Streamlit senden (Performance)

# ---------- CLIENT ----------
[client]
showErrorDetails = true             # Zeige Fehler-Details
toolbarMode = "developer"           # "auto"|"developer"|"viewer"|"minimal"
showSidebarNavigation = true

# ---------- RUNNER ----------
[runner]
magicEnabled = true
# Stabilität & Performance
fastReruns = true                   # Schnellere Reruns bei kleinen Änderungen
postScriptGC = true                 # Garbage Collection nach Script-Ausführung
# Memory Management
enforceSerializableSessionState = false  # Für komplexe Objekte in Session State

# ---------- THEME ----------
[theme]
base = "dark"                        # "light"|"dark"
primaryColor = "#00E5FF"             # Türkis/Cyan Akzent
backgroundColor = "#0B0F14"          # Dunkler Basis-Hintergrund
secondaryBackgroundColor = "#111720" # Sekundärer Hintergrund (Sidebar, Cards)
textColor = "#E6F7FF"                # Heller Text (leicht bläulich)
linkColor = "#4EA1FF"                # Link-Farbe
codeBackgroundColor = "#0B1220"      # Code-Block Hintergrund
font = "Nunito, sans-serif"          # Haupt-Schriftart
baseFontSize = 16                    # px
headingFont = "Nunito, sans-serif"   # Überschriften-Schriftart

# Font-Einbindung für Nunito
[[theme.fontFaces]]
family = "Nunito"
url = "https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;800&display=swap"
weight = "400"
style = "normal"

# ---------- LOGGER ----------
[logger]
level = "error"
messageFormat = "%(asctime)s %(message)s"
# Stabilität
enableRich = false                  # Einfaches Logging (weniger Overhead)

# ---------- DEPRECATION ----------
# Alle veralteten Optionen entfernt

# ---------- GLOBAL ----------
[global]
# Development vs Production
developmentMode = false              # Production-Modus (kompatibel mit server.port)
# Performance
showWarningOnDirectExecution = false # Keine Warnung bei direkter Ausführung
unitTest = false                    # Unit-Test-Modus deaktiviert
