# Core Package

# Configuration
from .config import (
    AppConfig,
    CacheConfig,
    DatabaseConfig,
    JobConfig,
    SecurityConfig,
    get_config,
    load_config,
    reload_config,
)

# Container System
from .containers import (
    ContainerConfig,
    ContainerRegistry,
    ContainerState,
    ErrorBoundary,
    PageContainer,
    PlaceholderContainer,
    StableContainer,
    TransitionContainer,
    create_page_container,
    create_placeholder,
    create_stable_container,
    get_container_registry,
)

# Database
from .database import (
    Base,
    DatabaseManager,
    Repository,
    UnitOfWork,
    get_conn,
    get_db_manager,
    init_database,
    run_tx,
)

# Form Management
from .form_manager import (
    FormAutoSave,
    FormDataModel,
    FormManager,
    FormRepository,
    FormSnapshot,
    FormSnapshotModel,
    FormState,
    FormValidationModel,
    FormValidator,
    ValidationResult,
    create_form,
    get_auto_save,
    get_form_manager,
    get_form_repository,
    get_form_validator,
    init_form_tables,
    redo_form,
    reset_form,
    save_form,
    save_form_now,
    undo_form,
    update_form_field,
    validate_form,
)
from .job_notifications import (
    EmailNotificationChannel,
    JobNotificationManager,
    LogNotificationChannel,
    NotificationChannel,
    WebhookNotificationChannel,
    add_notification_channel,
    get_notification_manager,
    notify_job_failure,
    notify_job_retry,
)
from .job_repository import (
    JobModel,
    JobRepository,
    JobResultModel,
    init_job_tables,
)

# Job System
from .jobs import (
    ErrorType,
    Job,
    JobManager,
    JobPriority,
    JobQueue,
    JobResult,
    JobStatus,
    ProgressCallback,
    cancel,
    enqueue,
    get_job_manager,
    poll,
    register_job_function,
)

# Logging
from .logging_system import (
    clear_correlation_id,
    get_correlation_id,
    get_log_level,
    get_logger,
    set_correlation_id,
    set_log_level,
    setup_structured_logging,
)

# Migration
from .migration_manager import (
    MigrationManager,
    create_migration,
    get_migration_manager,
    migrate,
    rollback,
)

# Navigation History
from .navigation_history import (
    Breadcrumb,
    HistoryEntry,
    NavigationAnalytics,
    NavigationHistory,
    get_navigation_analytics,
    render_breadcrumbs,
)

# Navigation System
from .router import (
    AuthenticationMiddleware,
    LoggingMiddleware,
    Middleware,
    NavigationEvent,
    NavigationEventType,
    Page,
    PermissionGuard,
    RoleGuard,
    Route,
    RouteGuard,
    Router,
    get_router,
    navigate,
)

# Security System
from .security import (
    AuthenticationAuditLog,
    # Authentication
    AuthenticationManager,
    AuthenticationResult,
    AuthenticationSession,
    AuthenticationStatus,
    # Authorization & RBAC
    AuthorizationManager,
    # Data Protection
    DataAccessLog,
    DataProtectionManager,
    DataRetentionPolicy,
    MFAManager,
    PasswordHasher,
    Permission,
    PermissionCache,
    PIIField,
    Role,
    # Security Monitoring
    SecurityEvent,
    SecurityEventType,
    SecurityMonitor,
    SecuritySeverity,
    SessionManager,
    ThreatDetector,
    User,
    # Initialization
    create_default_roles_and_permissions,
    get_authentication_manager,
    get_authorization_manager,
    get_data_protection_manager,
    get_data_retention_policy,
    get_mfa_manager,
    get_security_monitor,
    get_session_manager,
    get_threat_detector,
    init_all_security_tables,
    init_security_tables,
    log_data_access,
    require_permission,
    require_role,
)

# Session Management
from .session import (
    NavigationEntry,
    SessionPersistence,
    UserSession,
    bootstrap_session,
    cleanup_expired_sessions,
    get_current_session,
    get_session_persistence,
    persist_input,
    recover_session,
    save_session,
)
from .session_repository import (
    SessionModel,
    SessionRepository,
    init_session_tables,
)

# Widget Persistence
from .widget_persistence import (
    WidgetPersistenceEngine,
    WidgetStateModel,
    cleanup_old_widget_states,
    flush_widget_states,
    get_persistence_engine,
    init_widget_persistence_tables,
    recover_widget_states,
    save_widget_state,
)

# Widget Validation
from .widget_validation import (
    CustomRule,
    DateRangeRule,
    EmailRule,
    MaxLengthRule,
    MaxValueRule,
    MinLengthRule,
    MinValueRule,
    PatternRule,
    PhoneRule,
    RangeRule,
    RequiredRule,
    URLRule,
    ValidationEngine,
    ValidationRule,
    Validator,
    get_validation_engine,
    optional_number,
    optional_text,
    register_validator,
    required_date,
    required_email,
    required_number,
    required_phone,
    required_text,
    required_url,
    validate_widget,
)

# Controlled Widgets
from .widgets import (
    WidgetRegistry,
    WidgetState,
    clear_all_widget_states,
    clear_widget_state,
    get_all_widget_states,
    get_dirty_widgets,
    get_invalid_widgets,
    get_widget_registry,
    get_widget_state,
    mark_all_widgets_clean,
    s_checkbox,
    s_date,
    s_file,
    s_multiselect,
    s_number,
    s_radio,
    s_select,
    s_slider,
    s_text,
    s_textarea,
)

__all__ = [
    # Configuration
    "AppConfig",
    "CacheConfig",
    "DatabaseConfig",
    "JobConfig",
    "SecurityConfig",
    "get_config",
    "load_config",
    "reload_config",
    # Database
    "Base",
    "DatabaseManager",
    "Repository",
    "UnitOfWork",
    "get_conn",
    "get_db_manager",
    "init_database",
    "run_tx",
    # Logging
    "get_logger",
    "setup_structured_logging",
    "set_correlation_id",
    "get_correlation_id",
    "clear_correlation_id",
    "set_log_level",
    "get_log_level",
    # Migration
    "MigrationManager",
    "create_migration",
    "get_migration_manager",
    "migrate",
    "rollback",
    # Session Management
    "NavigationEntry",
    "SessionPersistence",
    "UserSession",
    "bootstrap_session",
    "cleanup_expired_sessions",
    "get_current_session",
    "get_session_persistence",
    "persist_input",
    "recover_session",
    "save_session",
    "SessionModel",
    "SessionRepository",
    "init_session_tables",
    # Navigation System
    "AuthenticationMiddleware",
    "LoggingMiddleware",
    "Middleware",
    "NavigationEvent",
    "NavigationEventType",
    "Page",
    "PermissionGuard",
    "RoleGuard",
    "Route",
    "RouteGuard",
    "Router",
    "get_router",
    "navigate",
    # Container System
    "ContainerConfig",
    "ContainerRegistry",
    "ContainerState",
    "ErrorBoundary",
    "PageContainer",
    "PlaceholderContainer",
    "StableContainer",
    "TransitionContainer",
    "create_page_container",
    "create_placeholder",
    "create_stable_container",
    "get_container_registry",
    # Navigation History
    "Breadcrumb",
    "HistoryEntry",
    "NavigationAnalytics",
    "NavigationHistory",
    "get_navigation_analytics",
    "render_breadcrumbs",
    # Controlled Widgets
    "WidgetRegistry",
    "WidgetState",
    "clear_all_widget_states",
    "clear_widget_state",
    "get_all_widget_states",
    "get_dirty_widgets",
    "get_invalid_widgets",
    "get_widget_registry",
    "get_widget_state",
    "mark_all_widgets_clean",
    "s_checkbox",
    "s_date",
    "s_file",
    "s_multiselect",
    "s_number",
    "s_radio",
    "s_select",
    "s_slider",
    "s_text",
    "s_textarea",
    # Widget Persistence
    "WidgetPersistenceEngine",
    "WidgetStateModel",
    "cleanup_old_widget_states",
    "flush_widget_states",
    "get_persistence_engine",
    "init_widget_persistence_tables",
    "recover_widget_states",
    "save_widget_state",
    # Widget Validation
    "CustomRule",
    "DateRangeRule",
    "EmailRule",
    "MaxLengthRule",
    "MaxValueRule",
    "MinLengthRule",
    "MinValueRule",
    "PatternRule",
    "PhoneRule",
    "RangeRule",
    "RequiredRule",
    "URLRule",
    "ValidationEngine",
    "ValidationRule",
    "Validator",
    "get_validation_engine",
    "optional_number",
    "optional_text",
    "register_validator",
    "required_date",
    "required_email",
    "required_number",
    "required_phone",
    "required_text",
    "required_url",
    "validate_widget",
    # Form Management
    "FormAutoSave",
    "FormDataModel",
    "FormManager",
    "FormRepository",
    "FormSnapshot",
    "FormSnapshotModel",
    "FormState",
    "FormValidationModel",
    "FormValidator",
    "ValidationResult",
    "create_form",
    "get_auto_save",
    "get_form_manager",
    "get_form_repository",
    "get_form_validator",
    "init_form_tables",
    "redo_form",
    "reset_form",
    "save_form",
    "save_form_now",
    "undo_form",
    "update_form_field",
    "validate_form",
    # Job System
    "ErrorType",
    "Job",
    "JobManager",
    "JobPriority",
    "JobQueue",
    "JobResult",
    "JobStatus",
    "ProgressCallback",
    "cancel",
    "enqueue",
    "get_job_manager",
    "poll",
    "register_job_function",
    "JobModel",
    "JobRepository",
    "JobResultModel",
    "init_job_tables",
    "EmailNotificationChannel",
    "JobNotificationManager",
    "LogNotificationChannel",
    "NotificationChannel",
    "WebhookNotificationChannel",
    "add_notification_channel",
    "get_notification_manager",
    "notify_job_failure",
    "notify_job_retry",
    # Security System
    "AuthenticationManager",
    "AuthenticationResult",
    "AuthenticationStatus",
    "MFAManager",
    "PasswordHasher",
    "SessionManager",
    "User",
    "AuthenticationSession",
    "AuthenticationAuditLog",
    "get_authentication_manager",
    "get_session_manager",
    "get_mfa_manager",
    "AuthorizationManager",
    "Permission",
    "PermissionCache",
    "Role",
    "get_authorization_manager",
    "require_permission",
    "require_role",
    "DataAccessLog",
    "DataProtectionManager",
    "DataRetentionPolicy",
    "PIIField",
    "get_data_protection_manager",
    "get_data_retention_policy",
    "log_data_access",
    "SecurityEvent",
    "SecurityEventType",
    "SecurityMonitor",
    "SecuritySeverity",
    "ThreatDetector",
    "get_security_monitor",
    "get_threat_detector",
    "create_default_roles_and_permissions",
    "init_all_security_tables",
    "init_security_tables",
]
